spring.application.name=notification-service

# MongoDB Connection URI
spring.data.mongodb.uri=mongodb://localhost:27017/notificationService

# MongoDB Connection Pool Settings
spring.data.mongodb.uuid-representation=standard

# Server Port
server.port=8080

